### PR TITLE
Support for waiting on file descriptors

### PR DESCRIPTION
**Pull request by jcheng5**
This PR adds a `later_fd` function. Where `later()` is for executing callbacks after (at least) a certain amount of time has elapsed, `later_fd()` is for executing callbacks when one or more of a set of file descriptors is ready for reading/writing. Without this ability, currently async (promise-based) I/O must rely on either background threads, or polling on the main thread.

This implementation is totally fake in that it actually relies on polling under the hood. I'm hoping it will be helpful in illustrating how such a function could be useful.

Here's an example of how it might be used:

```r
library(curl)
library(promises)

async_fetch <- function(url) {
  promises::promise(function(resolve, reject) {
    pool <- new_pool()
    curl_fetch_multi(
      url,
      done = resolve,
      fail = \(err) reject(simpleError(err)),
      pool = pool
    )
    
    loop <- function() {
      message("looping..")
      # Perform any pending reads/writes
      multi_run(timeout = 0.001, pool = pool)
      
      # Get file descriptors for still-pending operations
      fds <- multi_fdset(pool)
      # Put file descriptors in vector form, that's how later_fd wants them
      fdvec <- c(fds$reads, fds$writes, fds$exceptions)
      if (length(fdvec) > 0) {
        # Still have I/O we're waiting on. Wait until file descriptors are set
        # before trying again
        later::later_fd(\(ready) loop(), fdvec)
      }
    }
    loop()
  })  
}

async_fetch("https://cran.r-project.org") %...>% print()
```

This would eliminate wasteful polling (or it would if `later_fd` was done right) as the callback is only invoked when `multi_run` actually has work to do.

### CODE REVIEW

**Comment by shikokuchuo** [comment]
Just a small amendment: need to check if any pending operations from the value obtained by `multi_run()`. Also curl automatically suggests a timeout to use:

```r
library(curl)
library(promises)

async_fetch <- function(url) {
  promises::promise(function(resolve, reject) {
    pool <- new_pool()
    curl_fetch_multi(
      url,
      done = resolve,
      fail = \(err) reject(simpleError(err)),
      pool = pool
    )
    
    loop <- function() {
      message("looping..")
      # Perform any pending reads/writes
      if (multi_run(timeout = 0.001, pool = pool)$pending > 0) {
        # Get file descriptors for still-pending operations
        fds <- multi_fdset(pool)
        # Put file descriptors in vector form, that's how later_fd wants them
        fdvec <- c(fds$reads, fds$writes, fds$exceptions)
        # Wait until file descriptors are set before trying again
        later::later_fd(\(ready) loop(), fdvec, fds$timeout)
      }
    }

    loop()
  })  
}

async_fetch("https://cran.r-project.org") %...>% print()
```

**Comment by jcheng5** [comment]
Ah, good point. Not only is it more convenient to check `pending` but also I didn't realize that there might be non-fd reasons why you might need to call multi_run, which is why that `fds$timeout` exists. Watch out though, I think `fds$timeout` might be in milliseconds while the `later_fd` timeout is in seconds.

**Comment by shikokuchuo** [comment]
Good catch! Amended above. This is the result of me dropping into a browser to check what I'm getting, seeing `1` and thinking ah, secs... FYI it now seems to work reliably if you set `multi_run(timeout = 0)`, you'll actually see it looping a few times.

**Comment by jcheng5** [comment]
Superseded by #190

**Pull request closed without merging**
