### PR TITLE
Use configure script to detect RPi host

### PR DESCRIPTION
**Pull request by bearloga**
Addresses #109

### CODE REVIEW

**Comment by wch** [comment]
It would be better to detect directly when `-latomic` is required, because there may be other platforms that have the same problem. And it's possible that it will be fixed in some version of Raspbian OS.

You could do something like this:
* Attempt to compile a program without the flag.
  * If it succeeds, then `-latomic` isn't needed.
  * If it fails, attempt to compile a program with the flag.
    * If that succeeds, then `-latomic` is needed.
    * If it fails, then there's some other problem (like a missing compiler).

Also, the src/Makevars file can be removed.

**Comment by daissi** [comment]
I guess this can help here: https://github.com/NixOS/nix/pull/3114#issuecomment-540783953

**Comment by wch** [comment]
Closing this because it was superseded by #114.

**Comment by bearloga** [comment]
Thank you very much!

**Pull request closed without merging**
