### PR TITLE
Fix later_api.h is newer than installed later 

### PR DESCRIPTION
**Pull request by shikokuchuo**
This somehow errors with:

```r
Error in .Internal(dyn.load(x, as.logical(local), as.logical(now), "")) : 
  function 'execLaterFdNative' not provided by package 'later'
```

after going through the steps here: https://github.com/r-lib/later/pull/204#issue-2699393078.

@jcheng5 @wch

### CODE REVIEW

**Comment by jcheng5** [comment]
Well, you did better than Claude 3.5 Sonnet did--it hallucinated an `R_GetErrorHandler` and `R_SetErrorHandler` API--which would've been really cool! 😞

**Comment by shikokuchuo** [comment]
I haven't found the bug... or why yours seems to work when it's fundamentally the same structure!

**Comment by shikokuchuo** [comment]
Same error here: https://github.com/r-lib/later/actions/runs/12058747723/job/33626041239?pr=205#step:6:16
But it clearly does work in normal circumstances... there's obviously something I'm missing.

**Comment by shikokuchuo** [comment]
With the help of https://github.com/jcheng5/laterfdtest I can see now that it is working, and it's simply the error *message* that's being *printed* by `R_ToplevelExec()`, as Joe hinted at all along.

Porting across the helpful message dummy function, that now prints when expected, but *after* the first strange message. Unfortunately this seems unavoidable. To solve this we'd have to temporarily divert `stderr`.

**Comment by shikokuchuo** [comment]
This is superseded by the merged #204. But noting that it is possible to implement this in future - if somehow the trouble of diverting the stderr output from `R_ToplevelExec()` becomes the lesser evil.

**Pull request closed without merging**
